version: "3"
services:
  arkeod:
    image: arkeo
    build:
      dockerfile: ./Dockerfile
    ports:
      - "1317:1317"
      - "26657:26657"
    volumes:
      - "${HOME}/.arkeo:/root/.arkeo:rw"
    environment:
      NET: "mocknet"
    command: arkeod start

  sentinel:
    image: arkeo
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - "arkeod"
    ports:
      - "3636:3636"
    environment:
      NET: "mocknet"
      MONIKER: "n/a"
      WEBSITE: "n/a"
      DESCRIPTION: "n/a"
      LOCATION: "n/a"
      PORT: "3636"
      PROXY_HOST: "https://swapi.dev"
      SOURCE_CHAIN: "http://arkeod:1317"
      EVENT_STREAM_HOST: "arkeod:26657"
      FREE_RATE_LIMIT: 10
      FREE_RATE_LIMIT_DURATION: "1m"
      SUB_RATE_LIMIT: 10
      SUB_RATE_LIMIT_DURATION: "1m"
      AS_GO_RATE_LIMIT: 10
      AS_GO_RATE_LIMIT_DURATION: "1m"
      CLAIM_STORE_LOCATION: "${HOME}/.arkeo/claims"
    entrypoint: "/scripts/sentinel.sh"
    command: sentinel
    volumes:
      - "${HOME}/.arkeo:/root/.arkeo:rw"
      - "./scripts:/scripts"
