version: "3.6"
services:
  arkeod:
    hostname: arkeod
    build:
      dockerfile: ./Dockerfile
    ports:
      - "1317:1317"
      - "26656:26656"
      - "26657:26657"
    volumes:
      - ".arkeo:/.arkeo:rw"
    environment:
      NET: "mocknet"
    entrypoint: /scripts/genesis.sh
    command: arkeod start --home /.arkeo --pruning nothing

  arkeod-1:
    image: arkeo
    build:
      dockerfile: ./Dockerfile
    ports:
      - "1317"
      - "26657"
    environment:
      NET: "mocknet"
      PEER: arkeod
    entrypoint: /scripts/validator.sh
    command: arkeod start

  sentinel:
    image: arkeo
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - "arkeod"
    ports:
      - "3636:3636"
    environment:
      NET: "mocknet"
      MONIKER: "local"
      WEBSITE: "n/a"
      DESCRIPTION: "n/a"
      LOCATION: "n/a"
      PORT: "3636"
      PROXY_HOST: "https://swapi.dev"
      SOURCE_CHAIN: "http://arkeod:1317"
      EVENT_STREAM_HOST: "arkeod:26657"
      FREE_RATE_LIMIT: 10
      FREE_RATE_LIMIT_DURATION: "1m"
      SUB_RATE_LIMIT: 10
      SUB_RATE_LIMIT_DURATION: "1m"
      AS_GO_RATE_LIMIT: 10
      AS_GO_RATE_LIMIT_DURATION: "1m"
      CLAIM_STORE_LOCATION: "/root/.arkeo/claims"
      GAIA_RPC_ARCHIVE_HOST: "http://176.34.207.130:26657"
    entrypoint: "/scripts/sentinel.sh"
    command: sentinel
    volumes:
      - ".sentinel:/root/.arkeo:rw"
      - "./scripts:/scripts"
