apiVersion: v1
kind: Service
metadata:
  name: sentinel-service
  namespace: foundation
  labels:
    app: sentinel
spec:
  type: LoadBalancer
  ports:
    - port: 3636
      name: api
  selector:
    app: sentinel
